Update 231210: 
Site annotations corrected using hg38 version information (previously used hg37 version): modified in GEMMA_Output/add_loc

Update 231117: 
Request the consolidated ranking of each selected ageCpG across various models: see "ageCpGs' span-model ranks"

## Set up Environment

- Suitable for the integrated analysis of multiple "*.assoc.txt" files output by GEMMA.
- Place all "*.assoc.txt" files to be analyzed in the "./data/" directory of this IPython notebook; this directory must not contain any files other than those to be analyzed.

In [8]:
PATH_data = input('Please input the path of datas. Default: ./data/')
PATH_probe_doc = input('Please input the path of illumina product file.')#'/extData/Ken/Documents/infinium-methylationepic-v-1-0-b5-manifest-file_for_pandas.csv'

import pandas as pd
import matplotlib.pyplot as plt
import os
import re

Please input the path of datas. Default: "./data/" ./lmm26to29/
Please input the path of documentations. /extData/Ken/Documents/infinium-methylationepic-v-1-0-b5-manifest-file_for_pandas.csv

In [3]:
class GEMMA_Output:
    
    def __init__(self,note='None'):
        self.note = note
    
    def load_data(self,path,file_name):
        self.name = file_name.split('_')[0]
        df = pd.read_csv(path+file_name,sep='\t')
        self.data_df = df
        ranked_df = df.sort_values(by='p_wald')
        ranked_df.reset_index(inplace=True,drop=True)
        ranked_df['rank']=ranked_df.index
        ranked_df.set_index('rs',inplace=True)
        self.rank_df = ranked_df[['rank','p_wald']]
    
    def add_loc(self,doc_df):
        merge_df = pd.merge(doc_df[['Genome_Build','CHR_hg38','Start_hg38','SourceSeq','UCSC_RefGene_Name','UCSC_RefGene_Accession', 'Relation_to_UCSC_CpG_Island']],self.rank_df[['rank','p_wald']],how='inner',left_index=True,right_index=True)
        merge_df['single_UCSC_name'] = merge_df['UCSC_RefGene_Name'].str.replace('(;.*)','',regex=True)
        self.rank_df = merge_df.sort_values(by='p_wald')
    
    def select_sites(self,alpha=0.05):
        self.alpha = alpha
        self.threshold_p = alpha/len(self.rank_df.index)
        self.select_df = self.rank_df[self.rank_df['p_wald']<self.threshold_p]
    
    def show_info(self):
        print('Name:',self.name)
        print('Note:',self.note)
        print('alpha:',self.alpha)
        print('threshold_p (alpha/counts(sites)):',self.threshold_p)
        print('selected_sites_counts:',len(self.select_df.index))
        print('selected_sites:\n',self.select_df.head,sep='')
        print('------------------------------')

## Load Data

**Load Documentation**  
Load the probe annotation document（illumina product file）

In [4]:
doc_df = pd.read_csv(PATH_probe_doc,low_memory=False)
doc_df.set_index('Name',inplace=True)
print(doc_df.columns)
doc_df

Index(['IlmnID', 'AddressA_ID', 'AlleleA_ProbeSeq', 'AddressB_ID',
       'AlleleB_ProbeSeq', 'Infinium_Design_Type', 'Next_Base',
       'Color_Channel', 'Forward_Sequence', 'Genome_Build', 'CHR', 'MAPINFO',
       'SourceSeq', 'Strand', 'UCSC_RefGene_Name', 'UCSC_RefGene_Accession',
       'UCSC_RefGene_Group', 'UCSC_CpG_Islands_Name',
       'Relation_to_UCSC_CpG_Island', 'Phantom4_Enhancers',
       'Phantom5_Enhancers', 'DMR', '450k_Enhancer', 'HMM_Island',
       'Regulatory_Feature_Name', 'Regulatory_Feature_Group',
       'GencodeBasicV12_NAME', 'GencodeBasicV12_Accession',
       'GencodeBasicV12_Group', 'GencodeCompV12_NAME',
       'GencodeCompV12_Accession', 'GencodeCompV12_Group',
       'DNase_Hypersensitivity_NAME', 'DNase_Hypersensitivity_Evidence_Count',
       'OpenChromatin_NAME', 'OpenChromatin_Evidence_Count', 'TFBS_NAME',
       'TFBS_Evidence_Count', 'Methyl27_Loci', 'Methyl450_Loci',
       'Chromosome_36', 'Coordinate_36', 'SNP_ID', 'SNP_DISTANCE',
       'SNP_MinorAlleleFrequency', 'Random_Loci', 'MFG_Change_Flagged',
       'CHR_hg38', 'Start_hg38', 'End_hg38', 'Strand_hg38'],
      dtype='object')

,IlmnID,AddressA_ID,AlleleA_ProbeSeq,AddressB_ID,AlleleB_ProbeSeq,Infinium_Design_Type,Next_Base,Color_Channel,Forward_Sequence,Genome_Build,...,Coordinate_36,SNP_ID,SNP_DISTANCE,SNP_MinorAlleleFrequency,Random_Loci,MFG_Change_Flagged,CHR_hg38,Start_hg38,End_hg38,Strand_hg38
Name,,,,,,,,,,,,,,,,,,,,,
cg07881041,cg07881041,85713262,CTACAAATACAACACCCTCAACCCATATTTCATATATTATCTCATT...,NaN,NaN,II,NaN,NaN,CTGCACGCCTACTGCAGGTGCAGCACCCTCAGCCCATGTTTCATGT...,37.0,...,5187016,rs187313142,18,0.0002,NaN,False,chr19,5236004.0,5236006.0,+
cg18478105,cg18478105,46761277,AAATAAATTTCACTCTCAAATCCCAATCTCATACAACAAAACAAAA...,86644198.0,AAATAAATTTCGCTCTCAAATCCCAATCTCGTACGACGAAACGAAA...,I,C,Grn,TCCCGTCTTACGGGATGGATTTCGCTCTCAGGTCCCAGTCTCGTGC...,37.0,...,61318095,rs549944121,5,0.001797,NaN,False,chr20,63216297.0,63216299.0,+
cg23229610,cg23229610,21717843,ATAAAATTCTTTCCTTAAAAAACATTAAAACCAAAATAAACAAAAA...,NaN,NaN,II,NaN,NaN,GTTTCTGGACAGTAAAATTCTTTCCTTGAAGGACATTAGGGCCAAA...,37.0,...,6763712,rs545824288;rs527255711,40;12,0.000200;0.001198,NaN,False,chr1,6781064.0,6781066.0,+
cg03513874,cg03513874,29622133,ACAATAAAATAATAAAATCCCATCACTACTTACCCTCCTTAAATAA...,NaN,NaN,II,NaN,NaN,ATTGTGCCCACCTTGCTGCTGACAGTTAAGCATCACTAAAGTAGGA...,37.0,...,198011711,NaN,NaN,NaN,NaN,False,chr2,197438741.0,197438743.0,-
cg09835024,cg09835024,16745152,AATAAACACCAACCCCAAACCAATCTCACTTTATTAAATTACAAAA...,81631976.0,AATAAACGCCGACCCCGAACCGATCTCGCTTTATTAAATTACAAAA...,I,A,Red,AGCCCCGTCATAGGTGGGCGCCGACCCCGAGCCGATCTCGCTTTAT...,37.0,...,23982561,NaN,NaN,NaN,NaN,False,chrX,24054522.0,24054524.0,+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
cg23079522,cg23079522,98681180,AAAAAAATACCCAAAACACATTCTACTATTACTCCRTAATAACCCT...,NaN,NaN,II,NaN,NaN,AGGAGGAAGGTGGAAAGGTACCCAAGACACATTCTGCTGTTACTCC...,37.0,...,162052322,rs144073549;rs556478458,40;2,0.003594;0.000399,NaN,False,chr3,160851839.0,160851841.0,+
cg16818145,cg16818145,67613963,CAAAAAACRCTTAATAAACACCCAAAAAACTCCRTAAAAACTTCTA...,NaN,NaN,II,NaN,NaN,TTCCCTCGCTCCAGGAGACGCTTGGTGGGCACCCAGGAAGCTCCGT...,37.0,...,184264971,rs536633857;rs548317428,18;1,0.000200;0.000998,NaN,False,chr3,183064488.0,183064490.0,+
cg14585103,cg14585103,71743112,ATATCTAAATTTTCCAAAAACAATCCTAACTACATAACATAACATT...,NaN,NaN,II,NaN,NaN,GAGAAATAATAATGTCTGAATTTTCCAGAGACAGTCCTGGCTACAT...,37.0,...,140009790,rs562900783;rs528956739;rs11780350;rs147800551,48;46;42;18,0.000200;0.000200;0.033147;0.004193,NaN,False,chr8,138928364.0,138928366.0,+
cg10633746,cg10633746,72780862,CTTTAAATACTCCCAACCTATCTAAATTAAAACTCAACCCCATCTC...,NaN,NaN,II,NaN,NaN,ACCCGTGCCCTTTCCTGCTTCTCGGAGCTGGAAGGCTGTGGACTGA...,37.0,...,18105167,rs199681136;rs548989385;rs117304413,9;19;33,0.002000;0.000200;0.002995,NaN,False,chr17,18261127.0,18261129.0,-
cg12623625,cg12623625,99779128,AAAACATCTAAAACCAAATAACTCCCCATAATAAAACTATCCCRTA...,NaN,NaN,II,NaN,NaN,ACTGAGCAGGATGTGTTGTAGGATGGTGGGTAGAGACCAGGGAAGC...,37.0,...,17819510,rs566528435,13,0.0002,NaN,False,chr1,17620427.0,17620429.0,-

**Check the file list of datas to be analyzed**

In [5]:
LIST_files = os.listdir(PATH_data)
LIST_files

['LMM26_lmm.assoc.txt',
 'LMM27_lmm.assoc.txt',
 'LMM28_lmm.assoc.txt',
 'LMM29_lmm.assoc.txt',
 'LMM20_lmm.assoc.txt']

In [6]:
LIST_files.sort()
LIST_files

['LMM20_lmm.assoc.txt',
 'LMM26_lmm.assoc.txt',
 'LMM27_lmm.assoc.txt',
 'LMM28_lmm.assoc.txt',
 'LMM29_lmm.assoc.txt']

**Load Data**  
When reading data, the filename of each DEWAS result (for example, aabbcc.assoc.txt) (aabbcc) will automatically be available as the class instance name for invocation.

In [9]:
LIST_data = []

for i in range(len(LIST_files)):
    file_name = LIST_files[i]
    dataname = file_name.split('.')[0]
    print(i+1,'/',len(LIST_files),'Loading',file_name,'...')
    globals()[dataname] = GEMMA_Output()
    exec(dataname+'.load_data(PATH_data,file_name)')
    LIST_data.append(dataname)

print('\n','Data are loaded and callable with:',LIST_data,sep='\n')

1 / 5 Loading LMM20_lmm.assoc.txt ...
2 / 5 Loading LMM26_lmm.assoc.txt ...
3 / 5 Loading LMM27_lmm.assoc.txt ...
4 / 5 Loading LMM28_lmm.assoc.txt ...
5 / 5 Loading LMM29_lmm.assoc.txt ...


Data are loaded and callable with:
['LMM20', 'LMM26', 'LMM27', 'LMM28', 'LMM29']

**Add location info**  
Add the biological location and information of associated genes.

In [10]:
for i in range(len(LIST_data)):
    print(i+1,'/',len(LIST_data),'Processing loc info of',LIST_data[i],'...')
    exec(LIST_data[i]+'.add_loc(doc_df)')

1 / 5 Processing loc info of LMM20 ...
2 / 5 Processing loc info of LMM26 ...
3 / 5 Processing loc info of LMM27 ...
4 / 5 Processing loc info of LMM28 ...
5 / 5 Processing loc info of LMM29 ...

**Add/Modify Notes of datas**

In [11]:
for i in range(len(LIST_data)):
    print(i+1,'/',len(LIST_data),'Please input the note of',LIST_data[i],':')
    note = input()
    exec(LIST_data[i]+'.note = note')

1 / 5 Please input the note of LMM20 :

 continuous

2 / 5 Please input the note of LMM26 :

 D1090

3 / 5 Please input the note of LMM27 :

 D1585

4 / 5 Please input the note of LMM28 :

 D2080

5 / 5 Please input the note of LMM29 :

 D2575

## Significant Sites Selection

**Note**
- The threshold of p_value equals: alpha/counts(probes)  
- Alpha could be 0.5, 0.05 and so on. **Recomended and default value is 0.05**

In [12]:
alpha = float(input('Please input the alpha, 0.05 is recommended:')) #0.05

Please input the alpha, 0.05 is recommended: 0.05

In [13]:
for i in range(len(LIST_data)):
    exec(LIST_data[i]+'.select_sites(alpha)')
    exec(LIST_data[i]+'.show_info()')
    #print(i+1,'/',len(LIST_data),'The alpha of',LIST_data[i],'has been set to',alpha)

Name: LMM20
Note: continuous
alpha: 0.05
threshold_p (alpha/counts(sites)): 7.470804097586632e-08
selected_sites_counts: 599
selected_sites:
<bound method NDFrame.head of             Genome_Build CHR_hg38   Start_hg38  \
cg16867657          37.0     chr6   11044643.0
cg08097417          37.0     chr7  130734371.0
cg06639320          37.0     chr2  105399281.0
cg17268658          37.0     chr2  105399287.0
cg23606718          37.0     chr2  130756353.0
...                  ...      ...          ...
cg10757709          37.0     chr6     491346.0
cg23756236          37.0    chr19   37334669.0
cg04455430          37.0     chr1   50421247.0
cg22719623          37.0     chr6  154039596.0
cg10002915          37.0     chr4  148448022.0

                                                    SourceSeq  \
cg16867657  CGGCGGCTCAACGTCCACGGAGCCCCAGGAATACCCACCCGCTGCC...
cg08097417  TGTTTAACAGCCTCAGAAATTATCTTGTCTCCGCGTTCTTTCTTCT...
cg06639320  AGGGCTCCTTTCTTCGTGCCCTCCGGGTCTTGGGAGCACAGTAGTT...
cg17268658  CGCTCCCGATAACTACTGTGCTCCCAAGACCCGGAGGGCACGAAGA...
cg23606718  TCTCGGGGCCTTGGCGACTTACCGCTGGGGGCCCGCAGTGCAGCAG...
...                                                       ...
cg10757709  CGGACTGTTTTAGAAACTCTACTCATGACTGGCGGTCACCATGGTG...
cg23756236  CGCCTGGGCCACCGACCGGAAGTGTTTCTGACGTCAACGCTACACA...
cg04455430  GGCCCTCAAGGGCCACAAACGCTACTGTCGCTGGAAGGACTGCCTG...
cg22719623  CAAGTTGACCCAGGAACCGGGGCTGGGTGCTGGGGAGCAACTTGAG...
cg10002915  CGGAGCAGAGAACTAAGGGGTGGTTCTGCTAAAGCTGAAATAGAGA...

                                            UCSC_RefGene_Name  \
cg16867657                                             ELOVL2
cg08097417                                              KLF14
cg06639320                                FHL2;FHL2;FHL2;FHL2
cg17268658                                FHL2;FHL2;FHL2;FHL2
cg23606718    FAM123C;FAM123C;FAM123C;FAM123C;FAM123C;FAM123C
...                                                       ...
cg10757709                                        EXOC2;EXOC2
cg23756236                                               HKR1
cg04455430                                             DMRTA2
cg22719623  OPRM1;OPRM1;OPRM1;OPRM1;OPRM1;OPRM1;OPRM1;OPRM...
cg10002915                                                NaN

                                       UCSC_RefGene_Accession  \
cg16867657                                          NM_017770
cg08097417                                          NM_138693
cg06639320         NM_001039492;NM_001450;NM_201557;NM_201555
cg17268658         NM_001039492;NM_001450;NM_201555;NM_201557
cg23606718  NM_152698;NM_001105194;NM_001105195;NM_0011051...
...                                                       ...
cg10757709                                NR_073064;NM_018303
cg23756236                                          NM_181786
cg04455430                                          NM_032110
cg22719623  NM_001145286;NM_001145282;NM_001145281;NM_0011...
cg10002915                                                NaN

           Relation_to_UCSC_CpG_Island  rank         p_wald single_UCSC_name
cg16867657                      Island     0  1.295402e-139           ELOVL2
cg08097417                      Island     1   2.069133e-76            KLF14
cg06639320                      Island     2   3.137300e-59             FHL2
cg17268658                      Island     3   1.127112e-49             FHL2
cg23606718                      Island     4   3.993268e-43          FAM123C
...                                ...   ...            ...              ...
cg10757709                         NaN   594   6.988201e-08            EXOC2
cg23756236                      Island   595   7.148119e-08             HKR1
cg04455430                      Island   596   7.330112e-08           DMRTA2
cg22719623                      Island   597   7.361444e-08            OPRM1
cg10002915                     S_Shelf   598   7.410282e-08              NaN

[599 rows x 10 columns]>
------------------------------
Name: LMM26
Note: D1090
alpha: 0.05
threshold_p (alpha/counts(sites)): 8.200969682655278e-08
selected_sites_counts: 151
selected_sites:
<bound method NDFrame.head of             Genome_Build CHR_hg38   Start_hg38  \
cg04875128          37.0    chr15   31483691.0
cg27099280          37.0    chr15   72319862.0
cg08097417          37.0     chr7  130734371.0
cg02650266          37.0     chr4  146637086.0
cg00590036          37.0     chr6  158536400.0
...                  ...      ...          ...
cg09221867          37.0     chr4  133150507.0
cg01580888          37.0    chr19   33065153.0
cg26513192          37.0     chr1   94237821.0
cg19505546          37.0     chr5  139637677.0
cg15205547          37.0     chr7   23474727.0

                                                    SourceSeq  \
cg04875128  CGCCACGTACCCGCAGCAGAACCGCTCGCTGTCGTCGCAGAGCTAC...
cg27099280  CGCCGCGGCCATGTCCCCGCCCTGTCAGCCCTCCCGCCGGTCCCAC...
cg08097417  TGTTTAACAGCCTCAGAAATTATCTTGTCTCCGCGTTCTTTCTTCT...
cg02650266  GCTGTCCTCAGGAGCCGCCAGAGTGCTGGGGAAGGCGGCAGCAACG...
cg00590036  CGGGGGAGGAAGTGCAACACAAGGTCGTCTGCCGCCCAGGACAAAA...
...                                                       ...
cg09221867  CGGGAAAGAGGGGGGGTTGTCATTAATGTCCAGCACCTCGATCTCC...
cg01580888  CCTCGGGGTTGTCTGTGGGCGTCGTGGCTGACTCAACTTTGCGAGT...
cg26513192  CATCTGGCCATTAGCCGCATCTAGTCCTCAGGTGACTTTTCTCTGA...
cg19505546  GGGTGCAGAGGCCTAGGGCGGGCAGGCCGGCAGACTGGGGTCGGGC...
cg15205547  CGGTCAGCCAAGGGGCGGGCTCCACCCACGGACGCAGAACTGCTTT...

           UCSC_RefGene_Name  UCSC_RefGene_Accession  \
cg04875128            OTUD7A               NM_130901
cg27099280       CELF6;CELF6  NM_001172684;NM_052840
cg08097417             KLF14               NM_138693
cg02650266               NaN                     NaN
cg00590036           TMEM181               NM_020823
...                      ...                     ...
cg09221867     PCDH10;PCDH10     NM_032961;NM_020815
cg01580888             RHPN2               NM_033103
cg26513192          ARHGAP29               NM_004815
cg19505546               NaN                     NaN
cg15205547               NaN                     NaN

           Relation_to_UCSC_CpG_Island  rank        p_wald single_UCSC_name
cg04875128                      Island     0  2.914919e-30           OTUD7A
cg27099280                      Island     1  1.292691e-25            CELF6
cg08097417                      Island     2  4.623405e-21            KLF14
cg02650266                      Island     3  3.318059e-19              NaN
cg00590036                      Island     4  3.865417e-19          TMEM181
...                                ...   ...           ...              ...
cg09221867                      Island   146  7.198326e-08           PCDH10
cg01580888                      Island   147  7.688688e-08            RHPN2
cg26513192                     S_Shore   148  7.884809e-08         ARHGAP29
cg19505546                      Island   149  7.955965e-08              NaN
cg15205547                      Island   150  8.015619e-08              NaN

[151 rows x 10 columns]>
------------------------------
Name: LMM27
Note: D1585
alpha: 0.05
threshold_p (alpha/counts(sites)): 8.679545955591972e-08
selected_sites_counts: 371
selected_sites:
<bound method NDFrame.head of             Genome_Build CHR_hg38   Start_hg38  \
cg04875128          37.0    chr15   31483691.0
cg23606718          37.0     chr2  130756353.0
cg13108341          37.0    chr17   11705393.0
cg08097417          37.0     chr7  130734371.0
cg16419235          37.0     chr8   56448053.0
...                  ...      ...          ...
cg20997359          37.0     chr5   72139350.0
cg21328810          37.0    chr19   50325969.0
cg26229990          37.0    chr14   24332094.0
cg27191499          37.0     chr1  176567415.0
cg08885800          37.0     chr1  201114990.0

                                                    SourceSeq  \
cg04875128  CGCCACGTACCCGCAGCAGAACCGCTCGCTGTCGTCGCAGAGCTAC...
cg23606718  TCTCGGGGCCTTGGCGACTTACCGCTGGGGGCCCGCAGTGCAGCAG...
cg13108341  CGGCTCATTGATTTGCTCTGGGATTTGTTCCAAGAAAGGCTCTGCC...
cg08097417  TGTTTAACAGCCTCAGAAATTATCTTGTCTCCGCGTTCTTTCTTCT...
cg16419235  CAAAGGGCTGATTTCTACAGTCGCTAGGACCTGCAGCGGCGCTGCT...
...                                                       ...
cg20997359  CGAGAACCCAGGCTTCCAAGTTGCAGCAGCCCCAGTACACTGCACT...
cg21328810  CGGGCTGGTTTAACCCCTTACTCCAGAGTGTGTCAAAAGCAGAAGG...
cg26229990  CGTCCCTAGGGATGCCACAGTGTGGCACCACTTGTCCCACAATAGT...
cg27191499  CGTTGCAGAGCCTATAAGTTAATCAGTTAGTGAGTCATCATTCAAG...
cg08885800  CGGGGGCCGAGCTCAGCAGCTCTTGCAGGTACTTTATGTAGCGGAT...

                                          UCSC_RefGene_Name  \
cg04875128                                           OTUD7A
cg23606718  FAM123C;FAM123C;FAM123C;FAM123C;FAM123C;FAM123C
cg13108341                                            DNAH9
cg08097417                                            KLF14
cg16419235                                             PENK
...                                                     ...
cg20997359                                            MAP1B
cg21328810                                            KCNC3
cg26229990                                            ADCY4
cg27191499                                    PAPPA2;PAPPA2
cg08885800                                              NaN

                                       UCSC_RefGene_Accession  \
cg04875128                                          NM_130901
cg23606718  NM_152698;NM_001105194;NM_001105195;NM_0011051...
cg13108341                                          NM_001372
cg08097417                                          NM_138693
cg16419235                                       NM_001135690
...                                                       ...
cg20997359                                          NM_005909
cg21328810                                          NM_004977
cg26229990                                          NM_139247
cg27191499                                NM_021936;NM_020318
cg08885800                                                NaN

           Relation_to_UCSC_CpG_Island  rank        p_wald single_UCSC_name
cg04875128                      Island     0  6.757203e-48           OTUD7A
cg23606718                      Island     1  3.512854e-47          FAM123C
cg13108341                         NaN     2  2.434896e-39            DNAH9
cg08097417                      Island     3  1.108099e-35            KLF14
cg16419235                      Island     4  1.628125e-33             PENK
...                                ...   ...           ...              ...
cg20997359                         NaN   366  7.632025e-08            MAP1B
cg21328810                      Island   367  8.034914e-08            KCNC3
cg26229990                     N_Shore   368  8.215205e-08            ADCY4
cg27191499                         NaN   369  8.500938e-08           PAPPA2
cg08885800                      Island   370  8.617353e-08              NaN

[371 rows x 10 columns]>
------------------------------
Name: LMM28
Note: D2080
alpha: 0.05
threshold_p (alpha/counts(sites)): 9.05526427788795e-08
selected_sites_counts: 432
selected_sites:
<bound method NDFrame.head of             Genome_Build CHR_hg38   Start_hg38  \
cg13108341          37.0    chr17   11705393.0
cg04875128          37.0    chr15   31483691.0
cg03032497          37.0    chr14   60641508.0
cg21572722          37.0     chr6   11044660.0
cg04640687          37.0    chr13  102192393.0
...                  ...      ...          ...
cg22891601          37.0     chr2   81598589.0
cg04819580          37.0     chr7  150938437.0
cg07810190          37.0     chr6   32087268.0
cg18240400          37.0    chr10   45673148.0
cg24348981          37.0     chr2  107713092.0

                                                    SourceSeq  \
cg13108341  CGGCTCATTGATTTGCTCTGGGATTTGTTCCAAGAAAGGCTCTGCC...
cg04875128  CGCCACGTACCCGCAGCAGAACCGCTCGCTGTCGTCGCAGAGCTAC...
cg03032497  ATCTAACTCAACCCCTTTAGATATTCTTCCAGGTGGAATTATTGGA...
cg21572722  CGGAGCCCCAGGAATACCCACCCGCTGCCCAGATCGGCAGCCGCTG...
cg04640687  CGTGGTAATGACTCATGGACTGAATCAGCCATCTCAGAAGAGGCCA...
...                                                       ...
cg22891601  TGCCTGATGAATTTCACTTTGTAAATTCAGACCTGAAGCTGCTCAT...
cg04819580  CGCCTCAGGACTGCCTTTAAGGCATGACAGGAGCCACTGAGCCAAG...
cg07810190  CGCCTTCATCACCACCACAGGTAGTGTGGGCTGGGGCCACGGGACA...
cg18240400  GGCGCCTGATTTGCTGGAGATAGGCGATACAGGCAGACGCTGTCCA...
cg24348981  CGCCGTAAGTTGTTCAAAGCCCGTTACTACGCTTTGTGACTGCTCA...

           UCSC_RefGene_Name  UCSC_RefGene_Accession  \
cg13108341             DNAH9               NM_001372
cg04875128            OTUD7A               NM_130901
cg03032497               NaN                     NaN
cg21572722            ELOVL2               NM_017770
cg04640687             FGF14               NM_175929
...                      ...                     ...
cg22891601               NaN                     NaN
cg04819580               NaN                     NaN
cg07810190              TNXB               NM_019105
cg18240400     ANUBL1;ANUBL1  NM_001128324;NM_174890
cg24348981               NaN                     NaN

           Relation_to_UCSC_CpG_Island  rank        p_wald single_UCSC_name
cg13108341                         NaN     0  1.988398e-52            DNAH9
cg04875128                      Island     1  5.208654e-49           OTUD7A
cg03032497                     N_Shore     2  6.922186e-34              NaN
cg21572722                      Island     3  3.606926e-27           ELOVL2
cg04640687                         NaN     4  4.253593e-27            FGF14
...                                ...   ...           ...              ...
cg22891601                         NaN   427  8.536174e-08              NaN
cg04819580                         NaN   428  8.616493e-08              NaN
cg07810190                     N_Shore   429  8.623616e-08             TNXB
cg18240400                      Island   430  8.758509e-08           ANUBL1
cg24348981                         NaN   431  8.782802e-08              NaN

[432 rows x 10 columns]>
------------------------------
Name: LMM29
Note: D2575
alpha: 0.05
threshold_p (alpha/counts(sites)): 9.900107911176233e-08
selected_sites_counts: 358
selected_sites:
<bound method NDFrame.head of             Genome_Build CHR_hg38   Start_hg38  \
cg13108341          37.0    chr17   11705393.0
cg16532938          37.0     chr2  163728124.0
cg04875128          37.0    chr15   31483691.0
cg26921969          37.0     chr5   93612510.0
cg22736354          37.0     chr6   18122487.0
...                  ...      ...          ...
cg12597694          37.0    chr16    8183208.0
cg13245626          37.0     chr4   74633084.0
cg01344797          37.0    chr10  102413166.0
cg00481951          37.0     chr3  187669861.0
cg27603605          37.0    chr12  125517974.0

                                                    SourceSeq  \
cg13108341  CGGCTCATTGATTTGCTCTGGGATTTGTTCCAAGAAAGGCTCTGCC...
cg16532938  CGTGGACATTAGAAAGTGGTATTTTAGCTATATAAACATGTGACAG...
cg04875128  CGCCACGTACCCGCAGCAGAACCGCTCGCTGTCGTCGCAGAGCTAC...
cg26921969  CAAGCAAGACTCTCCACCCACAAACTGCATATTCTTTAAAGTCACT...
cg22736354  CTCGAGTGCAAGGTGTGCTTTGAGAAGTTTGGCCACCGGCAGCAGC...
...                                                       ...
cg12597694  TCTTGTCTCCTGCTTAAGGTTTCTGTTCTCTCATCTTCTATTGAGC...
cg13245626  AAGCAACATTTTTTCTTTCACATCATTTCCTAGTTACTTTAGCTTA...
cg01344797  CGCAAAGCCACCTGTCAGCCCAGAGACAGAGGCCGGAAACTCCTGG...
cg00481951  GTTTCAGCACCTGGGTCAGCGCTTCCCAGGGTCAGCACCAGGGATA...
cg27603605  ATACCACAGTGCCCAATATTGTGGCCACCAGCCACAAATGGCCATT...

           UCSC_RefGene_Name UCSC_RefGene_Accession  \
cg13108341             DNAH9              NM_001372
cg16532938              FIGN              NM_018086
cg04875128            OTUD7A              NM_130901
cg26921969               NaN                    NaN
cg22736354            NHLRC1              NM_198586
...                      ...                    ...
cg12597694               NaN                    NaN
cg13245626               NaN                    NaN
cg01344797               PSD              NM_002779
cg00481951               SST              NM_001048
cg27603605          TMEM132B              NM_052907

           Relation_to_UCSC_CpG_Island  rank        p_wald single_UCSC_name
cg13108341                         NaN     0  9.892833e-44            DNAH9
cg16532938                         NaN     1  7.399793e-36             FIGN
cg04875128                      Island     2  2.265307e-35           OTUD7A
cg26921969                         NaN     3  8.050800e-28              NaN
cg22736354                      Island     4  1.727440e-23           NHLRC1
...                                ...   ...           ...              ...
cg12597694                         NaN   353  9.575742e-08              NaN
cg13245626                         NaN   354  9.694301e-08              NaN
cg01344797                     S_Shelf   355  9.754396e-08              PSD
cg00481951                     N_Shore   356  9.857245e-08              SST
cg27603605                         NaN   357  9.886752e-08         TMEM132B

[358 rows x 10 columns]>
------------------------------

---

## Comparison of Significant Loci Rankings Across Models

In [17]:
uni_select_df = pd.DataFrame()

for i in range(len(LIST_data)):
    exec('temp_df='+LIST_data[i]+".select_df[['p_wald','rank']]")
    uni_select_df = pd.merge(uni_select_df,temp_df,left_index=True,right_index=True,how='outer')
    uni_select_df.rename(columns={'p_wald':LIST_data[i]+'_p_wald','rank':LIST_data[i]+'_rank'},inplace=True)

uni_select_df['!UCSC_gene_name']=doc_df.loc[uni_select_df.index]['UCSC_RefGene_Name'].str.replace('(;.*)','',regex=True)

In [78]:
uni_rank_df = uni_select_df[['!UCSC_gene_name','LMM20_rank','LMM26_rank','LMM27_rank','LMM28_rank','LMM29_rank']].sort_values(by='LMM20_rank')
uni_rank_df[:20]

,!UCSC_gene_name,LMM20_rank,LMM26_rank,LMM27_rank,LMM28_rank,LMM29_rank
cg16867657,ELOVL2,0.0,105.0,112.0,166.0,12.0
cg08097417,KLF14,1.0,2.0,3.0,10.0,NaN
cg06639320,FHL2,2.0,NaN,NaN,NaN,11.0
cg17268658,FHL2,3.0,NaN,NaN,NaN,24.0
cg23606718,FAM123C,4.0,22.0,1.0,8.0,NaN
cg21572722,ELOVL2,5.0,NaN,NaN,3.0,NaN
cg17110586,NaN,6.0,NaN,26.0,80.0,5.0
cg11071401,CACNA1G,7.0,NaN,NaN,NaN,NaN
cg07553761,TRIM59,8.0,NaN,NaN,NaN,NaN
cg22736354,NHLRC1,9.0,NaN,266.0,17.0,4.0
cg13206721,GPR158,10.0,5.0,8.0,15.0,NaN
cg09478021,CACNG7,11.0,8.0,259.0,321.0,251.0
cg07547549,SLC12A5,12.0,NaN,203.0,29.0,16.0
cg02650266,NaN,13.0,3.0,5.0,191.0,NaN
cg08637691,NaN,14.0,NaN,14.0,12.0,18.0
cg00590036,TMEM181,15.0,4.0,57.0,NaN,NaN
cg04875128,OTUD7A,16.0,0.0,0.0,1.0,2.0
cg27099280,CELF6,17.0,1.0,12.0,303.0,NaN
cg24797865,ITGB2,18.0,NaN,NaN,193.0,162.0
cg01899130,GCH1,19.0,NaN,NaN,61.0,46.0

In [ ]:
uni_rank_df.to_csv('./ageCpGs.csv')